---
services:
  url-shortener:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BASE_URL=http://localhost:3000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    volumes:
      # Mount data directory from host to persist CSV files
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--eval", "fetch('http://localhost:3000/api/health').then(() => process.exit(0)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
