---
services:
  url-shortener:
    image: joschi64/url-shortener:main
    networks:
      - kong-net
    volumes:
      # Mount data directory from host to persist CSV files
      - ./data:/app/data
    env_file:
      .env
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "--eval",
          "fetch('http://localhost:3000/api/health').then(() => process.exit(0)).catch(() => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  kong-net:
    external: true
